CREATE TABLE CLIENT (
    id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    pays VARCHAR2(50) NOT NULL,
    premium VARCHAR2(1) CHECK (premium IN ('O','N'))
);

CREATE TABLE CATEGORIE (
    id_categorie NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom_categorie VARCHAR2(50) NOT NULL,
    nb_produits NUMBER,
    date_creation DATE
);

CREATE TABLE COLIS (
    id_colis NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    date_creation DATE NOT NULL,
    pays_depart VARCHAR2(50),
    pays_destination VARCHAR2(50),
    date_estimee_arrivee DATE,
    id_client NUMBER,
    CONSTRAINT fk_colis_client FOREIGN KEY (id_client)
        REFERENCES CLIENT(id_client)
);

CREATE TABLE PRODUIT (
    id_produit NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nom_produit VARCHAR2(50) NOT NULL,
    prix NUMBER(10,2),
    rabais NUMBER(5,2),
    quantite NUMBER,
    id_colis NUMBER,
    id_categorie NUMBER,
    CONSTRAINT fk_produit_colis FOREIGN KEY (id_colis)
        REFERENCES COLIS(id_colis),
    CONSTRAINT fk_produit_categorie FOREIGN KEY (id_categorie)
        REFERENCES CATEGORIE(id_categorie)
);

--Client--
INSERT INTO CLIENT (nom, prenom, pays, premium) VALUES ('Bayan', 'Skyler', 'Canada', 'O');
INSERT INTO CLIENT (nom, prenom, pays, premium) VALUES ('Arous', 'Youcef', 'France', 'N');

--Categorie--
INSERT INTO CATEGORIE (nom_categorie, nb_produits, date_creation) VALUES ('Maison et cuisine', 1, DATE '2026-03-01');
INSERT INTO CATEGORIE (nom_categorie, nb_produits, date_creation) VALUES ('Electroniques', 2, DATE '2026-03-01');
INSERT INTO CATEGORIE (nom_categorie, nb_produits, date_creation) VALUES ('Mode', 1, DATE '2026-03-01');
INSERT INTO CATEGORIE (nom_categorie, nb_produits, date_creation) VALUES ('Beauté', 1, DATE '2026-03-01');

--Colis--
INSERT INTO COLIS (date_creation, pays_depart, pays_destination, date_estimee_arrivee, id_client) VALUES (DATE '2026-03-10', 'Canada', 'France', DATE '2026-03-18', 1);
INSERT INTO COLIS (date_creation, pays_depart, pays_destination, date_estimee_arrivee, id_client) VALUES (DATE '2026-03-12', 'Etats-Unis', 'Canada', DATE '2026-03-20', 2);

--Produit--
INSERT INTO PRODUIT (nom_produit, prix, rabais, quantite, id_colis, id_categorie) VALUES ('Air Fryer', 129.99, 10, 1, 1, 1);
INSERT INTO PRODUIT (nom_produit, prix, rabais, quantite, id_colis, id_categorie) VALUES ('Casque Bluetooth', 89.99, 15, 1, 1, 2);
INSERT INTO PRODUIT (nom_produit, prix, rabais, quantite, id_colis, id_categorie) VALUES ('Lunettes de soleil', 49.99, 20, 2, 2, 3);
INSERT INTO PRODUIT (nom_produit, prix, rabais, quantite, id_colis, id_categorie) VALUES ('Parfum', 79.99, 5, 1, 2, 4);
INSERT INTO PRODUIT (nom_produit, prix, rabais, quantite, id_colis, id_categorie) VALUES ('Ecouteurs sans fil', 149.99, 25, 1, 2, 2);


SELECT p.nom_produit, c.nom_categorie
FROM PRODUIT p
INNER JOIN CATEGORIE c
ON p.id_categorie = c.id_categorie;
